### PR TITLE
Count

### PR DESCRIPTION
**Pull request by VirgileD**
First implementation of the count API.

### CODE REVIEW

**Comment by rgrove** [comment]
Thanks for the patch!

When I run the online tests on ElasticSearch 0.18.6, I get the following failures:

```
  Client count() with a query
    ✗ should succeed
      » expected 1,
    got  0 (==) // online-tests.js:511

  Client count() with no query
    ✗ should succeed
      » expected 1,
    got  0 (==) // online-tests.js:521

  Client count() with two indices and no query
    ✗ should succeed
      » expected 3,
    got  0 (==) // online-tests.js:531

  Client count() with no type and no query
    ✗ should succeed
      » expected 2,
    got  0 (==) // online-tests.js:541
```

**Comment by VirgileD** [comment]
I've only tested this patch against ElasticSearch 0.17.6, which is our production version, and it worked right. I think I will need some time to make the upgrade and to make it work for 0.18.6, as the upgrade is not planned yet...

**Comment by VirgileD** [comment]
hello, we've finally upgraded to 0.18.7, and everything works fine for me:
$ curl http://localhost:9200/
{
  "ok" : true,
  "name" : "Golem",
  "version" : {
    "number" : "0.18.7",
    "snapshot_build" : false
  },
  "tagline" : "You Know, for Search",
  "cover" : "DON'T PANIC",
  "quote" : {
    "book" : "The Restaurant at the End of the Universe",
    "chapter" : "Chapter 20",
    "text1" : "The ship was rocking and swaying sickeningly as Ford and Zaphod tried to wrest control from the autopilot. The engines howled and whined like tired children in a supermarket."
  }
}%
                                                                                                                                                                               $ ./teardown.sh  
{"ok":true,"acknowledged":true}{"ok":true,"found":false,"_index":"_percolator","_type":"elastical-test-percolator-index","_id":"elastical-test-percolator-set","_version":1}{"ok":true,"found":false,"_index":"_percolator","_type":"elastical-test-percolator-index","_id":"elastical-test-percolator-get","_version":1}{"ok":true,"found":false,"_index":"_percolator","_type":"elastical-test-percolator-index","_id":"elastical-test-percolator-delete","_version":1}%                                                                         

$ ./setup.sh  
{"ok":true,"acknowledged":true}{"ok":true,"acknowledged":true}{"ok":true,"acknowledged":true}{"ok":true,"acknowledged":true}{"ok":true,"acknowledged":true}{"ok":true,"acknowledged":true}{"ok":true,"acknowledged":true}{"ok":true,"acknowledged":true}{"ok":true,"acknowledged":true}{"ok":true,"acknowledged":true}{"ok":true,"acknowledged":true}{"ok":true,"_index":"elastical-test-bulk","_type":"post","_id":"deleteme","_version":1}{"ok":true,"_index":"_percolator","_type":"elastical-test-bulk","_id":"perc","_version":1}{"ok":true,"_index":"elastical-test-get","_type":"post","_id":"1","_version":1}{"ok":true,"_index":"elastical-test-delete","_type":"post","_id":"1","_version":1}{"ok":true,"_index":"elastical-test-mapping","_type":"type","_id":"1","_version":1}{"ok":true,"_index":"elastical-test-mapping2","_type":"type","_id":"1","_version":1}{"ok":true,"_index":"elastical-test-mapping2","_type":"type","_id":"2","_version":1}{"ok":true,"_index":"elastical-test-mapping","_type":"type2","_id":"1","_version":1}{"ok":true,"acknowledged":true}{"ok":true,"acknowledged":true}{"ok":true,"_index":"_percolator","_type":"elastical-test-percolator-index","_id":"elastical-test-percolator-get","_version":2}{"ok":true,"_index":"_percolator","_type":"elastical-test-percolator-index","_id":"elastical-test-percolator-delete","_version":2}{"ok":true,"_shards":{"total":10,"successful":5,"failed":0}}{"ok":true,"_shards":{"total":10,"successful":5,"failed":0}}{"error":"IndexMissingException[[elastical-test] missing]","status":404}%                                                                   

$ vows online-tests.js --spec

? Elastical

  Client get() when the document does not exist
    ? should respond with an error
  Client get() when called with no options
    ? should get a document
  Client delete() when called with no options
    ? should delete the given document
  Client get() when the index does not exist
    ? should respond with an error
  Client bulk() when the index exists
    ? should succeed
  Client createIndex()
    ? should create an index
  Client putMapping() with no index
    ? should succeed
  Client getMapping() of a specific type within a specific index
    ? should succeed
  Client getMapping() of all types within a specific index
    ? should succeed
  Client getMapping() within multiple indices
    ? should succeed
  Client getMapping() of an unexisting index
    ? should return an IndexMissingException
  Client getMapping() of an unexisting type
    ? should return an TypeMissingException
  Client count() with a query
    ? should succeed
  Client count() with no query
    ? should succeed
  Client count() with two indices and no query
    ? should succeed
  Client count() with no type and no query
    ? should succeed
  Client refresh() with no index
    ? should succeed
  Client refresh() with multiple indices
    ? should succeed
  Client search() simple string query
    ? should return a hit
  Client search() simple object query
    ? should return a hit
  Client delete() when the document does not exist and options.ignoreMissing is not true
    ? should respond with an error
  Client delete() when the document does not exist and options.ignoreMissing is true
    ? should ignore the error
  Client get() options.fields when set to a String
    ? should get only the specified field
  Client get() options.fields when set to an Array
    ? should get only the specified fields
  Client get() options.ignoreMissing when true and the document does not exist
    ? should not respond with an error
  Client get() options.ignoreMissing when true and the index does not exist
    ? should not respond with an error
  Client get() options.type when a document with that type exists
    ? should get the document
  Client get() options.type when a document with that type does not exist
    ? should get an error
  Client indexExists() when called with a single index name which exists
    ? should respond with true
  Client indexExists() when called with a single index name which does not exist
    ? should respond with false
  Client indexExists() when called with multiple index names which all exist
    ? should respond with true
  Client indexExists() when called with multiple index names which do not all exist
    ? should respond with false
  Client putMapping() with multiple indices
    ? should succeed
  Client putMapping() with one index which does not exist
    ? should respond with an error
  Client refresh() with one index which exists
    ? should succeed
  Client refresh() with one index which does not exist
    ? should respond with an error
  Client index() when called with options.id
    ? should add or update the document with that id
  Client putMapping() with one index which exists
    ? should succeed
  Client createIndex() when the index already exists
    ? should provide an error
  Client index() when called with options.version set
    ? should automatically set version_type to "external"
  Client index() when called with no options
    ? should index the document
  Percolator Tests setPercolator()
    ? should return success
  Percolator Tests getPercolator()
    ? should return a hit
  Percolator Tests percolate() should return a match and the name of the percolator
    ? should return a hit
  Percolator Tests deletePercolator()
    ? should return true
  Percolator Tests percolate() should return a match and the name of the percolator even if doc is absent
    ? should return a hit
  Client (part deux) deleteIndex() when called with a single index name
    ? should delete the index
  Client (part deux) deleteIndex() when called with multiple index names
    ? should delete all the named indices

? OK » 48 honored (1.007s)

Could you please give it a new try?

**Comment by rgrove** [comment]
You're right, all tests pass now. Looks like the failures I saw before may have been caused by a problem with the teardown script that I fixed recently (it wasn't always being executed when running `make test`), so that could have caused those failures.

**Pull request merged**
